#dataChem
#arquivo feito por guilherme Del rio
def keywords (key):
    w = 'acentric factor '
    Tc = 'critical temperature '
    Pc = 'critical pressure '
    Vm = 'molar volume '
    Den = 'density '
    MM = 'molar mass '
    phase = 'phase '
    BP = 'boiling point '
    MP = 'melting point '
    SSpd = 'sound speed '
    formula = 'formula '
    CEC = 'cubic expansion coefficient '
    u = 'internal energy '
    h0 = 'enthalpy '
    S0 = 'entropy '
    Pv = 'vapor pressure '
    #CP can be either for the gas phase or liquid please specify after
    CP = 'specific heat cp ' 
    CV = 'cv '
    LSpd = 'light speed '
    odor = 'odor '
    ReID = 'refractive index '
    mi = 'viscosity '
    STen = 'surface tension '
    TCon = 'termal conductivity '